name: Create New Tag
run-name: ${{ github.actor }} is started to create new tag 🚀
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pull-requests: write
jobs:
  Bump-Version-And-Push-Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
